### ISSUE TITLE
running time cogaps

### ISSUE THREAD

**Issue by giovp** [FertigLab/CoGAPS#28]
Hi,

I'm trying to run cogaps for a sc-RNAseq dataset (5k genes x 7k cells), with this command:
```
k=70
cores=2
params <- new("CogapsParams")
params <- setParam(params, "nPatterns", k)
params <- setDistributedParams(params, nSets=cores)
#getParam(params, "nSets")

#set.seed(676)
result <- scCoGAPS(assays(scset)$logcounts, 
                   params, 
                   distributed="single-cell", 
                   singleCell=TRUE,
                   BPPARAM=BiocParallel::MulticoreParam(workers=cores),
                   messages=T)
```
Running time is quite high
```
setting distributed parameters - call this again if you change nPatterns

This is CoGAPS version 3.3.40
Running single-cell CoGAPS on 5000 genes and 7133 samples with parameters:

-- Standard Parameters --
nPatterns            70
nIterations          5000
seed                 295
singleCell           TRUE
sparseOptimization   FALSE
distributed          single-cell

-- Sparsity Parameters --
alpha          0.01
maxGibbsMass   100

-- Distributed CoGAPS Parameters --
nSets          2
cut            70
minNS          1
maxNS          3

Creating subsets...
set sizes (min, mean, max): (3566, 3566.5, 3567)
Running Across Subsets...

Loading Data...Done! (00:00:02)
    worker 1 is starting!
    worker 2 is starting!
-- Calibration Phase --
500 of 5000, Atoms: 74391(74157), ChiSq: 136910144, Time: 00:20:43 / 10:52:57
1000 of 5000, Atoms: 82704(92591), ChiSq: 135660368, Time: 00:48:20 / 11:12:02
1500 of 5000, Atoms: 90865(102149), ChiSq: 135199152, Time: 01:20:04 / 11:34:25
2000 of 5000, Atoms: 93763(115371), ChiSq: 134509280, Time: 01:52:35 / 11:40:22
2500 of 5000, Atoms: 97406(110010), ChiSq: 135169216, Time: 02:26:07 / 11:43:22
3000 of 5000, Atoms: 98089(116037), ChiSq: 134589984, Time: 03:01:02 / 11:47:17
3500 of 5000, Atoms: 96612(122988), ChiSq: 134334176, Time: 03:35:33 / 11:46:17
4000 of 5000, Atoms: 97890(122860), ChiSq: 134350288, Time: 04:11:01 / 11:46:30
4500 of 5000, Atoms: 93855(120010), ChiSq: 134670336, Time: 04:46:07 / 11:44:25
5000 of 5000, Atoms: 94880(124085), ChiSq: 134414736, Time: 05:19:54 / 11:38:54
-- Sampling Phase --
500 of 5000, Atoms: 94504(122858), ChiSq: 134543696, Time: 05:53:40 / 11:33:37
1000 of 5000, Atoms: 93654(128185), ChiSq: 134323920, Time: 06:28:42 / 11:30:54
1500 of 5000, Atoms: 95538(127658), ChiSq: 134265616, Time: 07:02:27 / 11:26:00
2000 of 5000, Atoms: 96887(126601), ChiSq: 134209024, Time: 07:37:26 / 11:23:14
```

However, as suggested by the vignettes, I only split the computation between 2 cores, to keep a consistent number of cells/genes. Would you recommend increasing the number of cores?
Also, I've noticed that the default `nIterations` changed between the bioconductor package version (around 500 I believe) and the latest github dev version (5000). What about choosing a value half way, like 2000? Would it dramatically affect the results?

Thank you for your time,

Giovanni

**Comment by sherman5** [comment]
Hi Giovanni,

The exact number of iterations needed is hard to know exactly, so typically we overestimate by a lot. 5000 is actually meant to be near a lower-bound for most cases. Based on the results you show here, I think more iterations are necessary. This is based on the number of atoms not stabilizing before the sampling phase, which is currently the best heuristic we have for determining if the algorithm has converged enough. Due to the run time, here are a few things I would suggest:

1) increase the number of sets/cores - currently there's about 3500 cells per subset of the data, it is likely the results will still be good with 1000-2000 cells per subset, so I would suggest using somewhere between 4-6 cores instead of 2

2) lower the value of nPatterns - I'm not sure if you have explored lower values already, but typically we start by running between 10-30 patterns. One of the nice features of scCoGAPS is that it will only keep the patterns found among multiple subsets of the data, so if you run on 30 patterns and it returns less than 25 or so - it's a good indicator 30 patterns is an upper bound for this data set. Otherwise you can re-run at a high number of patterns.

3) try `sparseOptimization=TRUE`, depending on the sparsity of your data this may make a huge difference. I would recommend running for a short period and comparing the run times with this on/off. Something like `nIterations=500` and `outputFrequency=100` so that you can see multiple time points.

Hopefully with those changes, running with more iterations will still have an acceptable run time. As I mentioned earlier, the best heuristic we have is looking at the number of atoms before the sampling phase and seeing if they've stablizied. I.e.

```
4000 of 5000, Atoms: 97890(122860), ChiSq: 134350288, Time: 04:11:01 / 11:46:30
4500 of 5000, Atoms: 93855(120010), ChiSq: 134670336, Time: 04:46:07 / 11:44:25
5000 of 5000, Atoms: 94880(124085), ChiSq: 134414736, Time: 05:19:54 / 11:38:54
-- Sampling Phase
```

In this section, the number of atoms (97k, 93k, 94k) and (122k, 120k, 124k) need to look closer together.

Let me know if this helps,
Tom

**Comment by giovp** [comment]
Hi Tom,

thank you for the prompt reply. Just a couple of more questions on this:

1. The number of subset is set according with the number of cores, is that correct? If so, what is a correlation estimate between the factors estimated from a distributed run compared to the one estimated from a single-core run?
2. I understand the heuristics about the number of atoms, but what would be a good agreement? e.g. 99k (100k) ?

Thanks again for the help,

Giovanni

**Comment by sherman5** [comment]
1. yes the number of subsets is set according with the number of cores. We are actively looking into ways to evaluate the results of distributed vs single-core, but at the moment I don't have any hard comparison between the two.

2. This actually points out to me a terrible design on our part. The number of atoms e.g. "97890(122860)" displayed are split up based on which matrix they correspond to. So in this example the A matrix has 97890 atoms and the P matrix has 122860 - they have nothing to do with each other and no agreement needs to exist between them. The agreement happens in the vertical direction, so we're looking for the number of atoms within each matrix to stabilize. Also to clarify, stabilizing is more important than agreement - i.e. if the number of atoms is continuously increasing we have probably not reached convergence even if the totals are "close" together. Once the number of atoms seems to be no longer increasing/decreasing in each of the respective matrices, the number of iterations is most likely sufficient. Unfortunately, this aspect of the algorithm can't be put into exact terms but we are working on a solution to it.

Tom

**Comment by giovp** [comment]
Hi Tom.

Thanks again for the reply. I'm trying to figure out then what should be the best way to assess and thus select the best model, across n random seed iterations with fixed k number of factors. Shall I just consider the ChiSquared value? I think it would be useful to also save the size of the atomic domains per (block?) of iteration.

Giovanni

**Comment by ejfertig** [comment]
We usually find that if the system has converged the solutions are fairly robust for a fixed k. This can be determined by looking both at mean chi2 and at the correlation between patterns after matching for random order. If they aren’t robust it can be either a sign of too few iterations for convergence or overdimensionalization.

**Comment by giovp** [comment]
Hi Elana,

thank you for the clarification, will take that into account for assessing stability.
Will close this issue.

Giovanni
